services:
  # Main FastAPI Web Service
  - type: web
    name: kenyan-legal-ai
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    envVars:
      # Application Configuration
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: API_V1_STR
        value: /api/v1
      
      # Security Configuration
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALGORITHM
        value: HS256
      
      # Database Configuration (PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: kenyan-legal-ai-db
          property: connectionString
      
      # Redis Configuration
      - key: REDIS_URL
        fromService:
          type: redis
          name: kenyan-legal-ai-redis
          property: connectionString
      
      # AWS Configuration (from secrets)
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      
      # Anthropic Configuration
      - key: ANTHROPIC_API_KEY
        sync: false
      
      # Hugging Face Configuration
      - key: HUGGING_FACE_TOKEN
        sync: false
      
      # Model Configuration
      - key: DEFAULT_AI_MODEL
        value: claude-sonnet-4
      - key: FALLBACK_AI_MODEL
        value: hunyuan
      - key: ENABLE_LOCAL_MODELS
        value: false  # Disabled in production for resource constraints
      - key: ENABLE_MODEL_FINE_TUNING
        value: false  # Disabled in production
      - key: MODEL_HEALTH_CHECK_INTERVAL
        value: 300
      - key: MODEL_CACHE_TTL
        value: 3600
      - key: MAX_MODEL_RETRIES
        value: 3
      - key: MODEL_TIMEOUT
        value: 60
      
      # Fine-tuning Configuration
      - key: FINE_TUNE_BATCH_SIZE
        value: 2
      - key: FINE_TUNE_EPOCHS
        value: 3
      - key: FINE_TUNE_LEARNING_RATE
        value: 5e-5
      - key: FINE_TUNE_DATA_PATH
        value: /opt/render/project/src/data/kenyan_legal_training.jsonl
      
      # Performance Monitoring
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      - key: MAX_ERROR_RATE_THRESHOLD
        value: 0.3
      - key: MAX_RESPONSE_TIME_THRESHOLD
        value: 60.0
      - key: MONITORING_WINDOW_SIZE
        value: 100
      
      # Rate Limiting
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 3600
      
      # Document Processing
      - key: MAX_DOCUMENT_SIZE
        value: 10485760  # 10MB
      - key: MAX_QUERY_LENGTH
        value: 2000
      
      # Vector Store Configuration
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: CHROMA_PERSIST_DIRECTORY
        value: /opt/render/project/src/chroma_db
      
      # CORS Configuration
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,https://www.your-frontend-domain.com
      - key: ALLOWED_METHODS
        value: GET,POST,PUT,DELETE,OPTIONS
      - key: ALLOWED_HEADERS
        value: Content-Type,Authorization,X-Requested-With
      
      # Orchestration Configuration
      - key: ENABLE_INTELLIGENCE_ENHANCEMENT
        value: true
      - key: ENHANCEMENT_MODE
        value: standard
      - key: ENABLE_RAG_ORCHESTRATION
        value: true
      - key: ENABLE_PROMPT_ENGINEERING
        value: true
      - key: ENABLE_ADAPTERS
        value: true
      - key: RAG_RETRIEVAL_STRATEGY
        value: hybrid
      - key: PROMPT_STRATEGY
        value: chain_of_thought
      - key: MAX_ENHANCEMENT_TIME
        value: 30.0
      - key: CACHE_ENHANCEMENTS
        value: true
    
    # Disk storage for persistent data
    disk:
      name: kenyan-legal-ai-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 5
    
    # Auto-deploy from main branch
    autoDeploy: true
    
    # Health check configuration
    healthCheck:
      path: /health
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    # Resource scaling
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80

  # PostgreSQL Database
  - type: pserv
    name: kenyan-legal-ai-db
    env: postgresql
    plan: starter
    databaseName: kenyan_legal_ai
    databaseUser: kenyan_legal_ai_user
    
  # Redis Cache
  - type: redis
    name: kenyan-legal-ai-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

# Environment-specific configurations
environments:
  production:
    services:
      - name: kenyan-legal-ai
        envVars:
          - key: ENVIRONMENT
            value: production
          - key: DEBUG
            value: false
          - key: LOG_LEVEL
            value: INFO
          - key: ENABLE_LOCAL_MODELS
            value: false
          - key: ENABLE_MODEL_FINE_TUNING
            value: false
        plan: standard  # Upgrade to standard plan for production
        
  staging:
    services:
      - name: kenyan-legal-ai
        envVars:
          - key: ENVIRONMENT
            value: staging
          - key: DEBUG
            value: true
          - key: LOG_LEVEL
            value: DEBUG
          - key: ENABLE_LOCAL_MODELS
            value: false
          - key: ENABLE_MODEL_FINE_TUNING
            value: true
        plan: starter
